@startuml
actor Оператор
participant RabbitMQ
participant MES
participant Redis
participant Database

Оператор -> MES: Получить список товаров
MES -> Redis: Запрос данных в кэше
alt cahce-hit
    Redis -> MES: Данные из кэша
    MES -> Оператор: Список товаров
else cahce-miss
    MES -> Database: Запрос данных из бд
    Database -> MES: Данные из бд
        MES -> Redis: Запись данных в кэш
    MES -> Оператор: Список заказов
end


alt update from operator
    Оператор -> MES: Взять заказ в работу
    MES -> Redis: Инвалидация данных
    MES -> Database: Запись новых данных

else update from rabbit
    RabbitMQ -> MES: Обновить заказ
    MES -> Redis: Инвалидация данных
    MES -> Database: Запись новых данных
end

@enduml